"use client";

import { useState } from "react";
import { Monitor, Smartphone, ArrowRight, MessageCircle, X, Check, Phone } from "lucide-react";
import { useAssessment } from "@/lib/assessment";
import { captureEvent } from "@/lib/analytics";

type DemoPage = "Home" | "Services" | "Request a visit";
export default function WebsiteDemo() {
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [page, setPage] = useState<DemoPage>("Home");
  const [chat, setChat] = useState(false);
  const [answer, setAnswer] = useState("");
  const [requested, setRequested] = useState(false);
  const [service, setService] = useState("AC repair");
  const { update } = useAssessment();
  const navigate = (next: DemoPage) => { setPage(next); setRequested(false); captureEvent("website_demo_navigated", { page: next }); };
  return (
    <section id="website-demo" className="scroll-mt-24 px-6 py-16 sm:py-24" aria-labelledby="website-demo-title">
      <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-6"><div className="max-w-2xl"><p className="font-mono text-xs uppercase tracking-[0.2em] text-gold">From a visit to a conversation</p><h2 id="website-demo-title" className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Do more than look at a website. Try one.</h2><p className="mt-4 leading-relaxed text-text-muted">Browse a sample local business, request a visit, and ask the assistant a question. Every interaction stays inside this demo.</p></div><div className="flex rounded-btn border border-line p-1" aria-label="Preview device">{(["desktop", "mobile"] as const).map(mode => <button key={mode} type="button" aria-pressed={device === mode} onClick={() => setDevice(mode)} className={`inline-flex min-h-11 items-center gap-2 rounded-btn px-3 text-sm ${device === mode ? "bg-gold text-bg" : "text-text-secondary"}`}>{mode === "desktop" ? <Monitor size={16} /> : <Smartphone size={16} />}{mode === "desktop" ? "Desktop" : "Mobile"}</button>)}</div></div>
        <div className="mt-8 rounded-panel border border-line bg-panel p-3 sm:p-5"><div className={`website-demo-preview mx-auto overflow-hidden rounded-xl border border-slate-300 bg-[#f8f5ef] text-[#20352e] ${device === "mobile" ? "max-w-[375px]" : "w-full"}`}>
          <div className="flex items-center gap-2 border-b border-slate-300 bg-[#e8e8e2] px-4 py-3 text-[10px] text-slate-600"><span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#bc6e55]" /><span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#d4b963]" /><span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#6d947c]" /><span className="ml-2 truncate">desert-and-pine.example / {page === "Home" ? "" : page.toLowerCase().replaceAll(" ", "-")}</span><span className="ml-auto shrink-0">DEMO</span></div>
          <div className="relative"><header className={`flex flex-wrap items-center justify-between gap-4 border-b border-[#20352e]/15 px-5 py-5 ${device === "desktop" ? "sm:px-8" : ""}`}><button type="button" onClick={() => navigate("Home")} className="text-left font-display text-lg font-semibold leading-snug">DESERT <span className="text-[#8f6034]">&</span> PINE<span className="block text-[9px] tracking-[0.25em]">HEATING & COOLING</span></button><nav aria-label="Sample website navigation" className="flex flex-wrap gap-4">{(["Home", "Services", "Request a visit"] as const).map(item => <button key={item} type="button" aria-current={page === item ? "page" : undefined} onClick={() => navigate(item)} className={`min-h-9 text-xs ${page === item ? "font-bold underline underline-offset-4" : ""}`}>{item}</button>)}</nav></header>
            <div className={`min-h-[370px] p-6 ${device === "desktop" ? "sm:p-10" : ""}`}>
              {page === "Home" && <div className={`grid items-center gap-8 ${device === "desktop" ? "md:grid-cols-[1.2fr_0.8fr]" : ""}`}><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#80572e]">Comfort, close to home.</p><h3 className={`mt-4 font-display font-semibold leading-tight ${device === "desktop" ? "text-3xl sm:text-5xl" : "text-3xl"}`}>Good neighbors.<br />Better air.</h3><p className="mt-4 max-w-md text-sm leading-relaxed text-[#58675e]">Thoughtful heating and cooling care for Phoenix homes. A straightforward service request, without the phone tag.</p><button type="button" onClick={() => navigate("Request a visit")} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#20352e] px-5 py-3 text-sm text-white">Request a service visit <ArrowRight size={16} /></button></div><div className="rounded-t-[100px] rounded-b-xl bg-[#e5decd] p-6 text-center"><div aria-hidden="true" className="mx-auto flex h-28 w-28 items-center justify-center rounded-full border-[12px] border-[#839584] text-4xl text-[#20352e]">✳</div><p className="mt-6 font-display text-xl">A little more comfortable.</p><p className="mt-2 text-xs leading-relaxed text-[#58675e]">Repair · Maintenance · Installation</p></div></div>}
              {page === "Services" && <><p className="text-[10px] uppercase tracking-widest text-[#80572e]">Care for every season</p><h3 className="mt-3 font-display text-3xl font-semibold">What can we help with?</h3><div className={`mt-6 grid gap-3 ${device === "desktop" ? "sm:grid-cols-3" : ""}`}>{["AC repair", "Seasonal tune-up", "System installation"].map((item, index) => <button key={item} type="button" onClick={() => { setService(item); navigate("Request a visit"); }} className="rounded-xl border border-[#20352e]/20 bg-white/60 p-5 text-left"><span className="text-xs text-[#80572e]">0{index + 1}</span><span className="mt-4 block font-display font-semibold leading-snug">{item}</span><span className="mt-4 block text-xs">Explore service →</span></button>)}</div></>}
              {page === "Request a visit" && <div className="max-w-lg"><p className="text-[10px] uppercase tracking-widest text-[#80572e]">A clearer next step</p><h3 className="mt-3 font-display text-3xl font-semibold">Let’s get you comfortable.</h3>{requested ? <div role="status" className="mt-6 rounded-xl border border-[#20352e]/20 bg-white/60 p-5"><Check className="text-[#436b4d]" /><p className="mt-3 font-semibold">Sample request captured.</p><p className="mt-2 text-sm leading-relaxed">The team would receive your {service.toLowerCase()} request and follow up to confirm a time. Nothing has been submitted or booked.</p><button type="button" className="mt-4 min-h-11 text-sm underline" onClick={() => setRequested(false)}>Try another request</button></div> : <form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); setRequested(true); }}><label className="block text-sm">Service<select value={service} onChange={event => setService(event.target.value)} className="mt-2 block w-full rounded-lg border border-[#20352e]/30 bg-white p-3">{["AC repair", "Seasonal tune-up", "System installation"].map(item => <option key={item}>{item}</option>)}</select></label><label className="block text-sm">Preferred time<select className="mt-2 block w-full rounded-lg border border-[#20352e]/30 bg-white p-3"><option>Morning</option><option>Afternoon</option><option>First available</option></select></label><p className="text-xs text-[#58675e]">No personal details needed. This is a simulation.</p><button type="submit" className="rounded-full bg-[#20352e] px-5 py-3 text-sm text-white">Send sample request</button></form>}</div>}
            </div>
            <div className="border-t border-[#20352e]/15 px-5 py-4"><button type="button" onClick={() => { setChat(!chat); setAnswer(""); }} aria-expanded={chat} aria-controls="sample-assistant" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#20352e] px-4 py-3 text-xs text-white"><MessageCircle size={16} />{chat ? "Close assistant" : "Ask the sample assistant"}</button></div>
            {chat && <div id="sample-assistant" className="mx-4 mb-4 rounded-xl border border-[#20352e]/20 bg-white p-5"><div className="flex items-center justify-between gap-3"><h4 className="font-semibold">Ember · Sample assistant</h4><button type="button" className="flex h-10 w-10 items-center justify-center" onClick={() => setChat(false)} aria-label="Close sample assistant"><X size={17} /></button></div><p className="mt-2 text-sm">Hi! What would you like to try?</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => setAnswer("In a connected site, I would use your approved business information to answer questions about hours and services.")} className="rounded-full border border-[#20352e]/30 px-3 py-3 text-xs">Ask about hours</button><button type="button" onClick={() => { navigate("Request a visit"); setChat(false); }} className="rounded-full border border-[#20352e]/30 px-3 py-3 text-xs">Request a visit</button><button type="button" onClick={() => setAnswer("The phone receptionist is a separate channel: a visitor can call your business number, and Ember can answer using your configured workflow. This sample does not place a call.")} className="inline-flex items-center gap-2 rounded-full border border-[#20352e]/30 px-3 py-3 text-xs"><Phone size={13} />How does calling work?</button></div>{answer && <p role="status" className="mt-4 rounded-lg bg-[#f8f5ef] p-3 text-sm leading-relaxed">{answer}</p>}</div>}
          </div>
        </div><p className="mt-3 text-center text-xs leading-relaxed text-text-muted">Fictional business · interactive prototype, not a live customer site · no data is sent.</p></div>
        <div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-text-muted">Your brand. Your services. One clear way to take the next step.</p><a href="#contact" onClick={() => { update({ pain: "both", step: 0 }); captureEvent("assessment_request", { placement: "website_demo" }); }} className="inline-flex items-center gap-2 text-sm font-semibold text-gold">Plan my website system <ArrowRight size={16} /></a></div>
      </div>
    </section>
  );
}

